export const CERTIFICATIONS = [
  {
    id: "item-0",
    title: "AI Engineer for Data Scientists Associate",
    issuer: "DataCamp",
    date: "2026",
    image: "/images/CoursesAndCertifications/ahmed-ayman-alhofys-ai-engineer-for-data-scientists-associate-certificate.jpg",
    link: "https://www.datacamp.com/certificate/AEDS0013645796856",
  },
  {
    id: "item-1",
    title: "SAP Certified Associate - SAP Generative AI Developer",
    issuer: "SAP",
    date: "2025",
    image: "/images/CoursesAndCertifications/ahmed-alhofy-sap-certified-associate-sap-generative-ai-developer.jpg",
    link: "https://www.credly.com/badges/f689025c-3b2e-4163-afa4-cd6abd275ee6/linked_in_profile",
  },
  {
    id: "item-2",
    title: "AWS Certified AI Practitioner",
    issuer: "AWS",
    date: "2025",
    image: "/images/CoursesAndCertifications/aws-certified-ai-practitioner-certificate-page-0001.jpg",
    link: "https://www.credly.com/badges/755dc8fb-e046-4945-b12e-d56e873e8659/linked_in_profile",
  },
  {
    id: "item-3",
    title: "IBM SkillsBuild Data Analytics Certificate",
    issuer: "IBM",
    date: "2025",
    image: "/images/CoursesAndCertifications/ibm-skillsbuild-data-analytics-certificate.jpg",
    link: "https://www.credly.com/badges/047fca36-195d-4782-9f0e-8d82b1d00c97/linked_in_profile",
  },
  {
    id: "item-4",
    title: "Oracle Cloud Infrastructure 2025 Certified AI Foundations Associate",
    issuer: "Oracle",
    date: "2025",
    image: "/images/CoursesAndCertifications/oracle-cloud-infrastructure-2025-certified-ai-foundations-associate.jpg",
    link: "https://catalog-education.oracle.com/ords/certview/sharebadge?id=5A50EC88B896ABCC9B1BFAD1B2574F3119FFA0F88048DA8C8DA1F59137AE63BA",
  },
  {
    id: "item-5",
    title: "Data Scientist Associate",
    issuer: "DataCamp",
    date: "2024",
    image: "/images/CoursesAndCertifications/data-scientist-associate.jpg",
    link: "https://www.datacamp.com/certificate/DSA0019876659394",
  },
  {
    id: "item-6",
    title: "Google Data Analytics Professional Certificate",
    issuer: "Coursera",
    date: "2024",
    image: "/images/CoursesAndCertifications/google-data-analytics-page-0001.jpg",
    link: "https://www.credly.com/badges/ba202583-d839-4158-9fde-cfff5c8c283b/linked_in_profile",
  },
  {
    id: "item-7",
    title: "AWS Academy Graduate - Machine Learning for Natural Language Processing",
    issuer: "AWS Academy",
    date: "2024",
    image: "/images/CoursesAndCertifications/aws-academy-graduate-aws-academy-machine-learning-for-natural-language-processing-page-0001.jpg",
    link: "https://www.credly.com/badges/6004bae9-fb5e-47f7-affa-80ca5c439df4/public_url",
  },
  {
    id: "item-8",
    title: "AWS Academy Graduate - Machine Learning Foundations",
    issuer: "AWS Academy",
    date: "2024",
    image: "/images/CoursesAndCertifications/aws-academy-graduate-aws-academy-machine-learning-foundations-page-0001.jpg",
    link: "https://www.credly.com/badges/bebffd29-e0af-4509-bde5-4961b6d08f7b/public_url",
  },
  {
    id: "item-9",
    title: "AWS Academy Graduate - Cloud Foundations",
    issuer: "AWS Academy",
    date: "2024",
    image: "/images/CoursesAndCertifications/aws-academy-graduate-aws-academy-cloud-foundations-page-0001.jpg",
    link: "https://www.credly.com/badges/1ef999ae-802b-4cba-829d-ebb3cbb75d77/public_url",
  },
  {
    id: "item-10",
    title: "AWS Academy Graduate - Data Engineering",
    issuer: "AWS Academy",
    date: "2024",
    image: "/images/CoursesAndCertifications/aws-academy-graduate-aws-academy-data-engineering-page-0001.jpg",
    link: "https://www.credly.com/badges/421fe942-73ea-4a56-9c9b-e9fa86f2daae/public_url",
  },
  {
    id: "item-11",
    title: "McKinsey.org Forward Program",
    issuer: "McKinsey.org",
    date: "2024",
    image: "/images/CoursesAndCertifications/mckinsey-forward-program-badge.jpeg",
    link: "https://www.credly.com/badges/a026e605-86ed-4f00-af62-99c535b0a150/public_url",
  },
];
