import type { Metadata } from "next";
import { Patrick_Hand, Dancing_Script } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import ClientBackgroundWrapper from "@/components/ClientBackgroundWrapper";
import { KBarProviderWrapper } from "@/components/kbar-provider";

const patrickHand = Patrick_Hand({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-patrick-hand",
});

const dancingScript = Dancing_Script({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--font-dancing-script",
});

export const metadata: Metadata = {
  title: "Ahmed Ayman",
  description: "Generated by Ahmed Ayman",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${patrickHand.variable} ${dancingScript.variable} antialiased`}
      >
        {" "}
        <ThemeProvider>
          <KBarProviderWrapper>
            <ClientBackgroundWrapper />
            {children}
          </KBarProviderWrapper>
        </ThemeProvider>
      </body>
    </html>
  );
}
